name: GitHub Deploy YandexCloud
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy backend files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "./backend"
          target: "/home/${{ secrets.SSH_USERNAME }}/dips/backend"

      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/dips/backend
            sudo docker compose down
            sudo docker rmi gateway_service
            sudo docker rmi bonus_service
            sudo docker rmi flight_service
            sudo docker rmi ticket_service
            sudo docker rmi auth_service
            sudo docker rmi statistics_service
            sudo docker rmi consumer_service
            sudo mkdir backend/auth_service/app/certs
            sudo docker compose up -d --build

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy frontend files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "./frontend/*"
          target: "/home/${{ secrets.SSH_USERNAME }}/dips/frontend"

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/dips/frontend
            sudo docker compose down
            sudo docker rmi dips-client
            sudo docker compose build --no-cache && sudo docker compose up -d